services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure:5

volumes:
  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge
