services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: on-failure:5

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure:5

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure:5

  adminer:
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: on-failure:5

  redis:
    build:
      context: ./requirements/bonus/redis
    container_name: redis
    ports:
      - 6379
    networks:
      - inception
    restart: on-failure:5

  ftp:
    build:
      context: ./requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure:5

  portainer:
    build:
      context: ./requirements/bonus/portainer
    container_name: portainer
    ports:
      - 9001:9000
    networks:
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: on-failure:5

volumes:
  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge
